// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Make(Config) {
  var context = React.createContext(Config[/* defaultValue */0]);
  var make = context.Provider;
  var Provider = /* module */[/* make */make];
  return /* module */[
          /* context */context,
          /* Provider */Provider
        ];
}

exports.Make = Make;
/* react Not a pure module */
